### ISSUE TITLE
довжина прізвища

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/html-horms-reg-exp#1]
https://github.com/DenisPitsul/html-horms-reg-exp/blob/efc28284ff8f12924f3574ba2a30416e0be79324/index.html#L39-L40
- `maxlength` і максимальна допустима довжина згідно регулярки протирічать одна одній. Згідно з регуляркою, дозволяється 32 + 1 + 32 = 65 символів максимум, а `maxlength` дозволить ввести лише 32.

**Comment by DenisPitsul** [comment]
Fixed in commits:
https://github.com/DenisPitsul/html-horms-reg-exp/commit/e14330c37e55965aaaaa0660f79fcc6702873e92
https://github.com/DenisPitsul/html-horms-reg-exp/commit/8da9cfb26645290149ffae1ebc0a5a5a95cd8947
