### ISSUE TITLE
валідація номера телефона

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/html-horms-reg-exp#2]
https://github.com/DenisPitsul/html-horms-reg-exp/blob/efc28284ff8f12924f3574ba2a30416e0be79324/index.html#L85
- якщо вказувати це для третьої частини номера, то логічно буде вказати аналогічну регулярку і для перших двох.

**Comment by DenisPitsul** [comment]
Fixed in commits:
https://github.com/DenisPitsul/html-horms-reg-exp/commit/e14330c37e55965aaaaa0660f79fcc6702873e92
https://github.com/DenisPitsul/html-horms-reg-exp/commit/8da9cfb26645290149ffae1ebc0a5a5a95cd8947
